version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: chatroom
      POSTGRES_PASSWORD: chatroom
      POSTGRES_DB: chatroom
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  kafka:
    image: bitnami/kafka:3.6
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
  app:
    build: .
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      APP_SERVER__HOST: 0.0.0.0
      APP_SERVER__PORT: 8080
    ports:
      - "8080:8080"

