[package]
name = "application"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../domain" }
async-trait = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
