TRUNCATE TABLE messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE room_members RESTART IDENTITY CASCADE;
TRUNCATE TABLE chat_rooms RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
